projects:
    reputometro:
        path: /home/ael/projects/reputometro.git
        rev:  public_html/rev.txt
        host: monitor.reputationlevel.com
        user: reputationlevel
        port: 54322
        password: ~
    reputation-level:
        path: /home/ael/projects/reel.git
        rev:  public/rev.txt
        host: beta.reputationlevel.com
        user: betareputationlevel
        port: 54322
        password: ~
    tuavisomx:
        path: /home/ael/projects/tuavisomx.git
        rev:  public_html/rev.txt
        host: tuaviso.com.mx
        user: tuaviso
        port: 54322
        password: ~
    tuavisolat:
        path: /home/ael/projects/tuavisolat.git
        rev:  public_html/rev.txt
        host: tuaviso.com.mx
        user: tuaviso-lat
        port: 54322
        password: ~
