app:
    log: /tmp/zetta.deploy.log
users:
    notify:
        zetta:
            - email: juan@reputationlevel.com
            - xmpp: zetaweb@gmail.com
        carlos:
            - email: carlos@reputationlevel.com
project:
    base-path: /home/zetta/Documents/git/
    port: 54322
    password: ~
projects:
    reputometro:
        path: reputometro.git
        rev:  public_html/rev.txt
        host: monitor.reputationlevel.com
        user: reputationlevel
        password: ~
    reputation-level:
        path: reel
        rev:  web/rev.txt
        host: beta.reputationlevel.com
        user: beta
    tuavisomx:
        path: tuavisomx.git
        rev:  public_html/rev.txt
        host: tuaviso.com.mx
        user: tuaviso
    tuavisolat:
        path: tuavisolat.git
        rev:  public_html/rev.txt
        host: tuaviso.com.mx
        user: tuaviso-lat
    test:
        path: deploy
        rev:  rev.txt
        host: localhost
        user: zetta
