app:
    log: /tmp/zetta.deploy.log
    mail:
        host: smtp.gmail.com
        port: 465
        security: ssl
        username: reputationlevel@gmail.com
        password: r3put4t10nD3f4ult
users:
    notify:
        jc:
            email: juan@tuaviso.com.mx
        zetta:
            email: zetaweb@gmail.com
            xmpp: zetaweb@gmail.com
project:
    base-path: /home/zetta/Documents/git/
    port: 54322
    password: ~
projects:
    reputometro:
        path: reputometro.git
        rev:  public_html/rev.txt
        host: monitor.reputationlevel.com
        user: reputationlevel
        password: ~
    reputation-level:
        path: reel
        rev:  web/rev.txt
        host: beta.reputationlevel.com
        user: beta
    tuavisomx:
        path: tuavisomx.git
        rev:  public_html/rev.txt
        host: tuaviso.com.mx
        user: tuaviso
    tuavisolat:
        path: tuavisolat.git
        rev:  public_html/rev.txt
        host: tuaviso.com.mx
        user: tuaviso-lat
    test:
        path: deploy
        rev:  rev.txt
        host: localhost
        user: zetta
